AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/HashAlignment:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 8

Naming/MethodParameterName:
  MinNameLength: 2

Style/ModuleFunction:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
