AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 2.5

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/HashAlignment:
  Enabled: false

Metrics:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2

Style/ModuleFunction:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
